name: Update snapshot

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run test -- -u
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "test/__snapshots__/."
          message: "update snapshot"
